name: ecommerce

description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.2
  sms_autofill: ^2.3.0
  pin_code_fields: ^8.0.1
  auto_size_text: ^3.0.0
  flutter_rating_bar: ^4.0.1
  image_picker: ^1.0.2
  fluttertoast: ^8.2.2
  grouped_list: ^5.1.2
  carousel_slider: ^4.0.0
  cached_network_image: ^3.2.1
  flutter_svg: ^2.0.7
  flutter_svg_provider: ^1.0.3
  smooth_page_indicator: ^1.1.0

  # DI & State management
  get_it: ^7.6.0
  get: ^4.6.5

  # Local
  get_storage: ^2.1.1

  # Network
  dio: ^5.3.2
  http_parser: ^4.0.2
  pretty_dio_logger: ^1.3.1
  connectivity_plus: ^5.0.2

  # Utils
  dartz: ^0.10.1
  equatable: ^2.0.5
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/InterBold.ttf
          weight: 700
        - asset: assets/fonts/InterSemiBold.ttf
          weight: 600
        - asset: assets/fonts/InterMedium.ttf
          weight: 500
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
        - asset: assets/fonts/InterLight.ttf
          weight: 300
    - family: Cairo
      fonts:
        - asset: assets/fonts/CairoBold.ttf
          weight: 700
        - asset: assets/fonts/CairoSemiBold.ttf
          weight: 600
        - asset: assets/fonts/CairoMedium.ttf
          weight: 500
        - asset: assets/fonts/CairoRegular.ttf
          weight: 400
    - family: DM Sans
      fonts:
        - asset: assets/fonts/DMSansBold.ttf
          weight: 700
        - asset: assets/fonts/DMSansRegular.ttf
          weight: 400
